[package]
name = "open_rust_map"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "open_rust_map"
path = "src/main.rs"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
geo = "0.26"
geo-types = "0.7"
hashbrown = "0.14"
indicatif = "0.17"
osmpbfreader = "0.16.0"
petgraph = "0.6"
rayon = "1.7"
tracing = "0.1"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
